; This code generated by com.zygateley.compiler

Data Section
    str0	DB	"Hello, World",10,""
    inputHandle	DD	0
    outputHandle	DD	0
    tempGlobal	DD	64 Dup 0

Code Section
start:
    ; Prepare environment for input and output
    ; Get input handle
    Push -10D                           ; Parameter for GetStdHandle
    Call GetStdHandle
    Mov [inputHandle], Eax              ; Save input handle
    ; Get output handle
    Push -11D                           ; Parameter for GetStdHandle
    Call GetStdHandle
    Mov [outputHandle], Eax             ; Save output handle
    
    ; Open scope
    ; Prepare if-then conditional
    ; If true, go to label0
    ; Finally, go to label1
    ; Prepare operand
    Mov Ebx, 0                          ; Clear register for new usage
    Mov Eax, 1D
    Mov Ebx, 1                          ; assemble operand TRUE
    Cmp Ebx, 0                          ; Determine if condition is false
    Jz > label1                         ; If condition is false, jump
    label0:
        ; Open scope
        ; Output
        ; Prepare operand
        Mov Ecx, 0                      ; Clear register for new usage
        Mov Eax, 13D
        Mov Ecx, Addr str0              ; assemble operand LITERAL
        ; Caller save registers
        Push Ebx                        ; Anonymous value added to stack
        Push Ecx                        ; Anonymous value added to stack
        Push 0                          ; Parameter for WriteConsoleA
        Push Addr tempGlobal            ; Parameter for WriteConsoleA
        Push Eax                        ; Parameter for WriteConsoleA
        Push Ecx                        ; Parameter for WriteConsoleA
        Push [outputHandle]             ; Parameter for WriteConsoleA
        Call WriteConsoleA
        ; Caller restore registers
        Pop Ecx                         ; Anonymous value removed from stack
        Pop Ebx                         ; Anonymous value removed from stack
        
        ; Close scope
        
    
    label1:
    
    ; Close scope
    
    Ret                                 ; Program finish
    
